### ISSUE TITLE
More modifiers

### ISSUE THREAD

**Issue by jcf** [sunaku/engrammer#5]
Hi @sunaku,

I've been working on my Engrammer layout for my Moergo and thought collaboration might be interesting.

One feature I've become dependent on is the use of Super and Hyper modifiers that I locate above my home row.

I see you have a one and two version of the ring finger keys, but there's nothing on the stronger index and middle fingers, where I've put hyper and super, respectively.

I've started work on extending the template you use to generate the DTSI file to support additional modifiers above the home row, but this left me wondering the following:

1. Will some people want modifiers accessible to their pinkies?

I most certainly do not. Emacs Pinky is a thing and motivated me to move towards home row mods, etc.

2. Will some people want modifiers under their home row?

I've only used the spots above my middle and index fingers on each hand, so maybe YAGNI should apply.

As this isn't something one can change from the JSON keymap alone, getting it right the first time and sharing might be best.

I'd love to hear your thoughts!

**Comment by sunaku** [comment]
I see, that's an interesting idea: :bulb: you'd need a dedicated Hyper key since you don't have any modifier on the pinky finger (and thus it's hard to hold all mods simultaneously since two of them are assigned to the same finger), correct? :thinking:

The home row mods arrangement in my keymap comes directly from the legendary Miryoku system, where each home row finger has a modifier assigned to it and thus you can chord all of them together to produce Hyper.  If that's infeasible or undesirable, then certainly a dedicated Hyper key (whether mod-tap or unadorned) might be helpful.  The main thing you'd have to watch out for is bilateral combinations: when you upgrade a normal key into a dual-function mod-tap key, you need to provision another layer for that key for bilateral combinations enforcement.

As for your questions:

1. Yes, but not more than one modifier per home row finger, per the Miryoku explanation above.
2. That's certainly possible: they can move the home row mods anywhere on the keyboard so long as the bilateral combination layers are also updated accordingly.  Alternatively, some people have used ZMK combos to activate sticky modifiers while avoiding the complexity of mod-tap keys.

By the way, this issue seems more related to my Glove80 keymap than the Engrammer layout itself, so we should move it to this repo instead: https://github.com/sunaku/glove80-keymaps

**Comment by jcf** [comment]
> The home row mods arrangement in my keymap comes directly from the legendary Miryoku system, where each home row finger has a modifier assigned to it and thus you can chord all of them together to produce Hyper. If that's infeasible or undesirable, then certainly a dedicated Hyper key (whether mod-tap or unadorned) might be helpful.

I have tried this but find my hands complain when holding down a subset of my four fingers — maybe because of historic overuse of my pinkies.

> By the way, this issue seems more related to my Glove80 keymap than the Engrammer layout itself, so we should move it to this repo instead: https://github.com/sunaku/glove80-keymaps

Apologies! Happy to follow up there.
